### ISSUE TITLE
[postgres] handle errors

### ISSUE THREAD

**Issue by rmannibucau** [kendarorg/the-protocol-master#10]
Hi,

I tested the runner with postgres executor to proxy oracle database to use it in Grafana.
Globally it works well while there is no execution error, when it happens - in my case Grafana triggers a discovery query (to get postgres version during configuration and tables/columns during query typing) which fails on oracle since tables are different - then the connection hangs and it seems it is no more working at all.
Patching the postgres executor to use valid queries solves the issue.
Indeed a better fix is to ensure the error is sent back to postgres using the wire protocol properly - in my case it helps to replace the postgres version query by hardcoding it but it is a particular, while the failures are properly forwarded I should be able to use the project without any patching at a very acceptable additional configuration cost.

Hope it makes sense

**Comment by kendarorg** [comment]
Finally someone else's use case :D  Using the " -v DEBUG " could give some more information. In the meantime, is there some exception thrown (hopefully)? Can you try with the "10-postgres-handle-errors" where i catch something earlier. If none of this work i'll setup an Oracle environment to simulate the error (PS what oracle version and what oracle driver version) Thanks :)

**Comment by rmannibucau** [comment]
@kendarorg I suspect it can be an issue with what grafana does also, for example it does a `SELECT 1` or `;` where `SELECT 1 from dual` should be used - or any "check" query.
There are also queries like these ones which can't work if the proxied database is not of the same type: https://github.com/grafana/grafana/blob/f900098cc9f5771c02b6189ba5138547b4f5e6c2/public/app/plugins/datasource/postgres/postgresMetaQuery.ts .

The error is generally something like "invalid query" - missing from for `;` for example, invalid table name for the discovery query - the previous link.

What is weird is that the grafana postgres client does not see the error message the protocol runner sends and then it just hangs cause the connection "exchange" is considered as not completed whereas the error was sent.

The used driver is https://github.com/lib/pq - I didn't get much issues using a jdbc client so I suspect it can be something more precise.

**Comment by kendarorg** [comment]
Seems like the behaviour of a not sent ReadyForQuery message is, so the client keep waiting till the timeout (thinking)

**Comment by kendarorg** [comment]
Or maybe the SQLSTATE "Code: the SQLSTATE code for the error (see [Appendix A](https://www.postgresql.org/docs/current/errcodes-appendix.html)). Not localizable. **Always present.**"  but ignored by the JDBC driver if not present

**Comment by kendarorg** [comment]
@rmannibucau New release built, let's see

**Comment by rmannibucau** [comment]
@kendarorg tested the new main and still the same behavior

testing running: `docker run --name=grafana --network host grafana/grafana:9.3.2` and `docker run --network host -e ORACLE_PASSWORD=password gvenzl/oracle-free` and configuring `-l 5432 -p postgres -v INFO -xw password -xl system -xc jdbc:oracle:thin:@localhost:1521/FREEPDB1`. Then I create a datasource in grafana and do a query using explore view.

**Comment by kendarorg** [comment]
trying now with the following compose
`version: "3"
services:
  jellyfin:
    image: grafana/grafana:9.3.2
    container_name: grafana 
    restart: unless-stopped
    ports:
      - "3000:3000"
  oracle:
    image: gvenzl/oracle-free
    container_name: oracle 
    restart: unless-stopped
    environment:
      - ORACLE_PASSWORD=password
    ports:
      - "1521:1521"`

**Comment by kendarorg** [comment]
I was able to test a connection from grafana to oracle..but of course it fails on creating the dashaboard

<pre>
java -cp "ojdbc11.jar;protocol-runner.jar" \
    org.springframework.boot.loader.JarLauncher \
    -p postgres -l 5432 \
    -xl system -xw password -xc jdbc:oracle:thin:@192.168.1.96:1521/FREEPDB1 \
    -xd test -v DEBUG
</pre>

And i notice that it requires the table names to fill the list of postgres table, plus, i think will follow the same thing for columns aggregation and aliases

<pre>
select quote_ident(table_name) as "table" from information_schema.tables
    where quote_ident(table_schema) not in ('information_schema',
                             'pg_catalog',
                             '_timescaledb_cache',
....
</pre>

Probably a good approach could be adding a kind of config file to intercept requests doing some kind of regexp search/replace. Or a way to add hooks to the runner

**Comment by rmannibucau** [comment]
@kendarorg i think the fakeQueries could be configurable to help/map the queries but still, a failure shouldn't corrupt the connection, isnt it?

**Comment by kendarorg** [comment]
Should not create problems in theory :(  I noticed now that a CancelRequest is issued, let me check how it is handled (even by the driver)
<pre>
2024-05-02 12:56:29,799 [DEBUG] CID:2 [SERVER][TX]: ErrorResponse Tags:  [ProtoContext]
2024-05-02 12:56:29,800 [DEBUG] CID:2 [SERVER][TX]: ReadyForQuery Tags:  [ProtoContext]
2024-05-02 12:56:29,805 [INFO] CID: [SERVER] Accepted connection from /192.168.1.96:41132 [TcpServer] 
2024-05-02 12:56:29,868 [DEBUG] CID:3 [SERVER][RX]: CancelRequest Tags:  [ProtoContext] 
</pre>

**Comment by kendarorg** [comment]
What evidence you have of the connection closing abruptly? Because every time i try to add a query on explore, it connects correctly (albeit failing for the missing metadata tables)

**Comment by kendarorg** [comment]
...and can you send me the queries you patched so i can put all attention on them :D

**Comment by kendarorg** [comment]
Ok, now i think i get it
