### ISSUE TITLE
Implement healthchecks

### ISSUE THREAD

**Issue by rmannibucau** [kendarorg/the-protocol-master#13]
The client often has some health check but it would be neat to have it on the runner-backend side too to close the client connection early when it disconnects (network issue most of the time, database restart etc).
Guess by default it can use `connection.isValid(someTimeout)` for the healthcheck.
Not 100% sure if the "while idle", "on borrow" or "on return" strategy must be configurable - I know I use the first two for the apps I work with to either secure the connection reliability or to optimize the perfs with a good compromise but never the last one.

**Comment by kendarorg** [comment]
@rmannibucau if you wanna give a try: https://github.com/kendarorg/the-protocol-master/tree/13-implement-healthchecks
