### ISSUE TITLE
Connection to mongodb proxy using navicat timed out

### ISSUE THREAD

**Issue by gaowl714** [kendarorg/the-protocol-master#19]
Navicat发送OpQuery Hello请求时不会传helloOk字段导致没有对应的执行方法
![image](https://github.com/kendarorg/the-protocol-master/assets/70258173/f78431e9-2898-41a6-a04c-acac7bc2ae36)

**Comment by kendarorg** [comment]
Hi @gaowl714 what was the resolution? Just to keep a note, since you can't imagine how many quirks there are in protocol documentations :( ...and drivers implementations, like mandatory things considered optional and vice versa, or "oppps this behaviour is not documented"

**Comment by gaowl714** [comment]
I don't have a great resolution and I just did it casually. you can look at lines 32 and 33 of the comment code, but there is no reference value.(Sorry, I was going to type Chinese first and then translate it into English, but I clicked the wrong button, which is the reason why I closed)

**Comment by kendarorg** [comment]
No problem :) We all survive with google translator :)
